### ISSUE TITLE
millis() overflow problem.

### ISSUE THREAD

**Issue by qnxsgwy** [Dlloydev/QuickPID#52]
"if (msNow > nextSwitchTime) { nextSwitchTime = msNow + debounce;"
 is used in the PID_RelayOutput example,
When nextSwitchTime overflows, the comparison results for the next cycle will be wrong.

//should use
if(millis() - lastMillis >= interval){
//and NOT like
if(millis() >= lastMillis + interval){

**Comment by Dlloydev** [comment]
Thank you for pointing this out.

While developing and testing the function, the 50 day overflow issue wasn't considered.  This is because the miscalculated PID sample would represent a very small slice of the window size and any thermal systems using this slower time proportioning output method would also have a very slow rate of temperature rise. 

Even so, I'll take a look at updating the function to prevent the overflow issue.

**Comment by Dlloydev** [comment]
Converting this to discussion. Will do some additional testing and possible update for a future release.
